### ISSUE TITLE
Allow for different text when hovering over a node.

### ISSUE THREAD

**Issue by joseberlines** [timkpaine/ipydagred3#9]
Hi. 

I am experimenting with ipydagred3 and it is really great. so little code and "voila" integrated in Jupyter.

Would it be possible that when hovering over the nodes in the graph a different text can be displayed that the text contained in the node itself (to offer the user extra information rather)

Thanks.

**Comment by timkpaine** [comment]
Nodes and edges support `name` which is basically their unique identifier, `label` which is what goes in the box or next to the line, and `tooltip` which is what goes in the tooltip. tooltips default to `name` if no tooltip or label, else `label` if no tooltip. 

So basically, just add kwarg `tooltip=...` when creating a node or label.

**Comment by joseberlines** [comment]
Perfect. works wonderfully.
